"""Initial migration 2

Revision ID: 08574b7b1531
Revises: 
Create Date: 2025-01-27 00:05:23.591538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08574b7b1531'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('nepali_date', sa.String(length=10), nullable=True),
    sa.Column('holiday_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index('idx_holiday_date', ['date'], unique=False)
        batch_op.create_index('idx_holiday_type', ['holiday_type'], unique=False)
        batch_op.create_index('idx_holiday_year_month', ['year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_holidays_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_nepali_date'), ['nepali_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_holidays_year'), ['year'], unique=False)

    op.create_table('saturdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saturdays', schema=None) as batch_op:
        batch_op.create_index('idx_saturday_date', ['date'], unique=False)
        batch_op.create_index('idx_saturday_year_month', ['year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_saturdays_date'), ['date'], unique=True)
        batch_op.create_index(batch_op.f('ix_saturdays_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_saturdays_year'), ['year'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('validation_date', sa.DateTime(), nullable=True),
    sa.Column('invalid_dates', sa.JSON(), nullable=True),
    sa.Column('total_invalid', sa.Integer(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_results')
    with op.batch_alter_table('saturdays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saturdays_year'))
        batch_op.drop_index(batch_op.f('ix_saturdays_month'))
        batch_op.drop_index(batch_op.f('ix_saturdays_date'))
        batch_op.drop_index('idx_saturday_year_month')
        batch_op.drop_index('idx_saturday_date')

    op.drop_table('saturdays')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_year'))
        batch_op.drop_index(batch_op.f('ix_holidays_nepali_date'))
        batch_op.drop_index(batch_op.f('ix_holidays_month'))
        batch_op.drop_index(batch_op.f('ix_holidays_date'))
        batch_op.drop_index('idx_holiday_year_month')
        batch_op.drop_index('idx_holiday_type')
        batch_op.drop_index('idx_holiday_date')

    op.drop_table('holidays')
    # ### end Alembic commands ###
